project_id = "xfptozziptcpvhtkezba"

[functions.paypal]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.fetch-forum-economicus]
verify_jwt = false

[functions.send-chronicle-email]
verify_jwt = false
